# Generated by Django 6.1 on 2026-09-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_url', models.URLField(blank=True, null=True)),
                ('project_image_url', models.URLField(blank=True, null=True)),
                ('tech_stack', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
