# Generated by Django 6.1 on 2026-09-21 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_experience_started_at_alter_project_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 21, 14, 11, 45, 948101, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
